- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github Actions integrations
    action: "upload"
    ###### Verify these locations ######
    app_location: "/" # The root directory of your app source code. Adjust if needed.
    api_location: "" # Your Azure Functions code location. Leave blank if no API.
    output_location: "build" # The directory of your build output relative to app_location. Adjust if needed.
    ###### End Verify ######
  # Add other inputs like app_build_command if necessary
